Repository jenkinsci/winstone, pull requests merged in 2020-10, with the labels that each got.

#118 [JENKINS-63713] Add a LowResourceMonitor to Jetty Winstone
  src/main/java/winstone/Ajp13ConnectorFactory.java
  src/main/java/winstone/ConnectorFactory.java
  src/main/java/winstone/Http2ConnectorFactory.java
  src/main/java/winstone/HttpConnectorFactory.java
  src/main/java/winstone/HttpsConnectorFactory.java
  src/main/java/winstone/Launcher.java
  src/test/java/winstone/FormSubmissionTest.java
  src/test/java/winstone/HttpConnectorFactoryTest.java
  src/test/java/winstone/HttpsConnectorFactoryTest.java
  src/test/java/winstone/LauncherTest.java
  src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
  src/test/java/winstone/realm/ArgumentsRealmTest.java
Labels: enhancement

#123 Remove obsolete Dependabot v1 configuration file
  .dependabot/config.yml
Labels: chore

#125 downgrade jetty to 9.4.30.v20200611
  pom.xml
Labels: bug, dependencies

#126 `--requestHeaderSize` argument is added to the help string.
  src/main/resources/winstone/LocalStrings.properties
Labels: chore, documentation

#124 [JENKINS-63958] - Update Jetty from 9.4.32.v20200930 to 9.4.33.v20201020
  pom.xml
Labels: bug, dependencies
