Repository jenkinsci/winstone, pull requests merged in 2020-01, with the labels that each got.

#86 Various regressions from earlier code cleanup
  src/main/java/winstone/HostConfiguration.java
  src/main/java/winstone/Launcher.java
  src/main/java/winstone/WinstoneSession.java
Labels: bug

#87 [JENKINS-57888] - Restore `java.util.logging.config.file` property support (regression in 5.4)
  src/main/java/winstone/Launcher.java
Labels: regression-fix

#90 [JENKINS-60821] set the name of Jetty's thread pool
  src/main/java/winstone/Launcher.java
Labels: enhancement

#91 [JENKINS-60857] Using SslContextFactory.Server
  Jenkinsfile
  pom.xml
  src/main/java/winstone/AbstractSecuredConnectorFactory.java
  src/ssl/wildcard.jks
  src/ssl/wildcard.txt
  src/test/java/winstone/HttpsConnectorFactoryTest.java
Labels: bug
