Repository jenkinsci/winstone, pull requests merged in 2022-08, with the labels that each got.

#249 Write port value atomically
  pom.xml
  src/main/java/winstone/Launcher.java
  src/test/java/winstone/HttpConnectorFactoryTest.java
Labels: bug, ready-for-merge

#253 Improve comment and error message
  src/main/java/winstone/HostConfiguration.java
Labels: internal

#256 Remove redundant `project.build.sourceEncoding` property
  pom.xml
Labels: skip-changelog
