Repository jenkinsci/winstone, pull requests merged in 2022-09, with the labels that each got.

#259 Re-enable `spotbugs` and fix some issues
  pom.xml
  src/main/java/winstone/HostConfiguration.java
  src/main/java/winstone/HostGroup.java
  src/main/java/winstone/Http2ConnectorFactory.java
  src/main/java/winstone/Launcher.java
  src/main/java/winstone/Logger.java
  src/main/java/winstone/accesslog/SimpleAccessLogger.java
  src/main/java/winstone/cmdline/Option.java
  src/main/java/winstone/realm/ArgumentsRealm.java
  src/main/java/winstone/realm/FileRealm.java
  src/spotbugs/spotbugs-excludes.xml
Labels: internal

#267 Remove unneeded SUREFIRE-1226 workaround
  pom.xml
Labels: skip-changelog, internal

#266 Remove redundant version
  pom.xml
Labels: dependencies, java

#268 Upgrade Rhino from 1.7R2 to 1.7R5
  pom.xml
Labels: dependencies, java

#269 Remove unneeded managed dependency entry
  pom.xml
Labels: dependencies, java

#270 "Error" is misspelled
  src/main/resources/winstone/LocalStrings.properties
Labels: skip-changelog

#273 Drop `commons-io` dependency in favor of native Java Platform functionality
  pom.xml
  src/test/java/winstone/AbstractWinstoneTest.java
  src/test/java/winstone/FormSubmissionTest.java
  src/test/java/winstone/HttpsConnectorFactoryTest.java
  src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
Labels: test

#272 Remove redundant `maven-antrun-plugin` version
  pom.xml
Labels: dependencies, java

#274 Manage both SLF4J API and SLF4J implementation versions
  pom.xml
Labels: dependencies, java

#276 Prefer `assertThrows` to try/fail/catch
  src/test/java/winstone/AbstractWinstoneTest.java
  src/test/java/winstone/realm/ArgumentsRealmTest.java
Labels: test

#277 Migrate from HttpUnit to native Java Platform functionality
  pom.xml
  src/test/java/winstone/AbstractWinstoneTest.java
  src/test/java/winstone/FormSubmissionTest.java
  src/test/java/winstone/HttpConnectorFactoryTest.java
  src/test/java/winstone/LauncherTest.java
  src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
  src/test/java/winstone/realm/ArgumentsRealmTest.java
  src/test/java/winstone/testCase/HttpConnectorTest.java
  src/test/java/winstone/testCase/load/LoadTest.java
  src/test/java/winstone/testCase/load/LoadTestThread.java
Labels: test

#278 Run tests with JUnit Jupiter
  pom.xml
Labels: test

#279 Sort dependencies
  pom.xml
Labels: skip-changelog

#280 Exclude SpotBugs annotations from shaded JAR
  pom.xml
Labels: internal

#283 Enable JaCoCo in CI runs
  pom.xml
Labels: test

#282 [JENKINS-69638] HTTP/2 broken after Jetty 10 upgrade
  pom.xml
  src/main/java/winstone/Http2ConnectorFactory.java
  src/test/java/winstone/Http2ConnectorFactoryTest.java
Labels: regression-fix

#285 Remove outdated HTTP/2 documentation
  README.md
Labels: documentation

#287 Remove unused JSP options
  README.md
  src/main/java/winstone/Launcher.java
  src/main/java/winstone/cmdline/Option.java
  src/main/resources/winstone/LocalStrings.properties
Labels: removed, upgrade-guide-needed

#288 Remove dead references to `executable-war`
  README.md
  src/main/java/winstone/WinstoneSession.java
  src/main/resources/winstone/LocalStrings.properties
Labels: documentation
