Repository jenkinsci/winstone, pull requests merged in 2022-02, with the labels that each got.

#193 Update `Jenkinsfile`
  .github/workflows/maven.yml
  Jenkinsfile
Labels: chore

#194 Update POM URLs
  pom.xml
Labels: skip-changelog

#196 Use UTF-8 source encoding
  pom.xml
Labels: internal

#195 Run tests on Windows
  Jenkinsfile
Labels: test

#197 Test annotations should be in test scope
  pom.xml
Labels: test

#198 Fix IDE warnings
  pom.xml
  src/main/java/winstone/AbstractSecuredConnectorFactory.java
  src/main/java/winstone/Ajp13ConnectorFactory.java
  src/main/java/winstone/ConnectorFactory.java
  src/main/java/winstone/HostConfiguration.java
  src/main/java/winstone/HostGroup.java
  src/main/java/winstone/Http2ConnectorFactory.java
  src/main/java/winstone/HttpConnectorFactory.java
  src/main/java/winstone/HttpsConnectorFactory.java
  src/main/java/winstone/Launcher.java
  src/main/java/winstone/Logger.java
  src/main/java/winstone/WinstoneResourceBundle.java
  src/main/java/winstone/accesslog/SimpleAccessLogger.java
  src/main/java/winstone/cmdline/CmdLineParser.java
  src/main/java/winstone/cmdline/Option.java
  src/main/java/winstone/realm/ArgumentsRealm.java
  src/main/java/winstone/realm/FileRealm.java
  src/main/java/winstone/tools/WinstoneControl.java
  src/test/java/winstone/AbstractWinstoneTest.java
  src/test/java/winstone/FormSubmissionTest.java
  src/test/java/winstone/HttpsConnectorFactoryTest.java
  src/test/java/winstone/LauncherTest.java
  src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
  src/test/java/winstone/realm/ArgumentsRealmTest.java
  src/test/java/winstone/testCase/HttpConnectorTest.java
  src/test/java/winstone/testCase/WinstoneResourceBundleTest.java
  src/test/java/winstone/testCase/load/LoadTest.java
  src/test/java/winstone/testCase/load/LoadTestThread.java
Labels: internal

#199 Add missing `@Override` annotations
  src/main/java/winstone/Ajp13ConnectorFactory.java
  src/main/java/winstone/HttpConnectorFactory.java
  src/main/java/winstone/HttpsConnectorFactory.java
  src/main/java/winstone/Launcher.java
  src/main/java/winstone/ShutdownHook.java
  src/main/java/winstone/accesslog/SimpleAccessLogger.java
  src/main/java/winstone/tools/WinstoneControl.java
  src/test/java/winstone/TrustEveryoneManager.java
  src/test/java/winstone/TrustManagerImpl.java
  src/test/java/winstone/testApplication/filters/TimingFilter.java
  src/test/java/winstone/testApplication/filters/WriteAfterServletFilter.java
  src/test/java/winstone/testApplication/listeners/SessionListener.java
  src/test/java/winstone/testApplication/servlets/CountRequestsServlet.java
  src/test/java/winstone/testApplication/servlets/UnavailableServlet.java
  src/test/java/winstone/testCase/load/LoadTestThread.java
Labels: internal

#200 Fix high-threshold SpotBugs warnings
  pom.xml
  src/main/java/winstone/AbstractSecuredConnectorFactory.java
  src/main/java/winstone/Launcher.java
  src/main/java/winstone/Logger.java
  src/main/java/winstone/WinstoneSession.java
  src/main/java/winstone/accesslog/SimpleAccessLogger.java
  src/main/java/winstone/cmdline/CmdLineParser.java
  src/test/java/winstone/testCase/HttpConnectorTest.java
Labels: internal

#201 Use HTTPS URL in POM
  pom.xml
Labels: internal

#202 Clean up imports
  src/main/java/winstone/cmdline/CmdLineParser.java
  src/main/java/winstone/realm/ArgumentsRealm.java
  src/main/java/winstone/realm/FileRealm.java
  src/test/java/winstone/AbstractWinstoneTest.java
  src/test/java/winstone/FormSubmissionTest.java
  src/test/java/winstone/HttpConnectorFactoryTest.java
  src/test/java/winstone/HttpsConnectorFactoryTest.java
  src/test/java/winstone/LauncherTest.java
  src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
  src/test/java/winstone/realm/ArgumentsRealmTest.java
Labels: internal

#204 Remove redundant group id
  pom.xml
Labels: chore

#203 Remove automatic self signed cert if tls specified but no keystore
  src/main/java/winstone/AbstractSecuredConnectorFactory.java
  src/test/java/winstone/HttpsConnectorFactoryTest.java
Labels: breaking
