Repository jenkinsci/winstone, pull requests merged in 2022-06, with the labels that each got.

#226 [JENKINS-66745] Winstone: http/2 port not backward compatible with ALPN http/1.1 clients
  src/main/java/winstone/Http2ConnectorFactory.java
Labels: bug

#229 Make test less flaky
  src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
Labels: skip-changelog

#230 Bump jetty.version from 9.4.46.v20220331 to 9.4.48.v20220622 (#227)
  pom.xml
Labels: dependencies

#181 Upgrade Jetty to 10.0.11
  .github/dependabot.yml
  README.md
  pom.xml
  src/main/java/winstone/AbstractSecuredConnectorFactory.java
  src/main/java/winstone/HostGroup.java
  src/main/java/winstone/Http2ConnectorFactory.java
  src/main/java/winstone/HttpsConnectorFactory.java
  src/main/java/winstone/Launcher.java
  src/main/java/winstone/ServerConnectorBuilder.java
  src/main/java/winstone/cmdline/Option.java
  src/main/resources/winstone/LocalStrings.properties
  src/test/java/winstone/HttpsConnectorFactoryTest.java
  src/test/resources/jul.properties
Labels: enhancement

#234 Remove unused resource bundle key
  src/main/resources/winstone/LocalStrings.properties
Labels: chore

#233 Rework 5s sleep with 100ms intervals
  src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
Labels: test, ready-for-merge

#232 Remove ability to load pem cert for winstone
  README.md
  src/main/java/winstone/AbstractSecuredConnectorFactory.java
  src/main/java/winstone/cmdline/Option.java
  src/main/resources/winstone/LocalStrings.properties
  src/test/java/winstone/HttpsConnectorFactoryTest.java
Labels: breaking

#236 Add Java 17 on CI
  Jenkinsfile
Labels: chore

#237 Use Java 11 language features where possible
  src/main/java/winstone/HostConfiguration.java
  src/test/java/winstone/FormSubmissionTest.java
Labels: skip-changelog

#239 Update `README`
  README.md
Labels: documentation
